### ISSUE TITLE
Respect ShowInSearch=0

### ISSUE THREAD

**Issue by chillu** [ichaber/silverstripe-swiftype#20]
It's a setting that's available in core on all SIlverStripe sites. It probably shouldn't be, since sites do search in many different ways, but that's hard to untangle now: https://github.com/silverstripe/silverstripe-framework/issues/1633

So given there's a checkbox visible to authors in the CMS, they should reasonably expect that it also applies to this module. Can we tell Swiftype to avoid indexing a specific page via HTML metadata?

**Comment by chrispenny** [comment]
Sounds reasonable.

Swiftype respects `<meta name="robots" content="noindex">`, so we can add that.
