### ISSUE TITLE
Use of updated vs. published_at

### ISSUE THREAD

**Issue by madmatt** [ichaber/silverstripe-swiftype#24]
This module defines one field: `SwiftypeMetaTagPublishedAt`, which uses the value of `LastEdited` to populate the field in Swiftype.

However, that seems the exact opposite of what Swiftype is expecting according to their [Crawler-based engine schema design](https://swiftype.com/documentation/site-search/guides/schema-design#crawler) documentation, which says that instead we should:
* Use `Created` for `published_at`, and
* Use `LastEdited` for `updated_at`

Before I make a PR for this change, does anyone know if there's a reason why it's done this way? I assume it's this way for a reason, but I'm not sure exactly why.

/cc @chrispenny, @blueo and @ichaber who might know more specifics on this.

Thanks!

**Comment by blueo** [comment]
could be an oversight but I read those docs as `updated_at` is the last time it was 'crawled' by swiftype not updated by us - and `published_at` defaults to the last time swiftype detected a change - which seems more like LastEdited than Created to me. Open to disagreement on that assessment - the docs aren't super clear as to what it wants vs what it presents

**Comment by chrispenny** [comment]
Yea, these fields are quite confusing, and this topic has been brought up previously (#19).

My thoughts reflect that of @blueo. Based on the docs, I believe that `published_at` is meant to be the last edited date. From Swiftype:

>If not defined via a meta tag, the value will be the last time an update to the page was detected during a crawl.

**Comment by chrispenny** [comment]
Is this one still an issue, @madmatt, or is it ok for me to close?

**Comment by madmatt** [comment]
Fine with me, let's close it
